### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by simplymathematics** [simplymathematics/data-skills#1]
- [x] Create Database
- [x] Document Database
- [x] Test Database

**Comment by ghh2001** [comment]
HI, Jun (John) Pan and I manually created the relational database via Excel on occupation (33 of them) and their skills. Sorry about the cheating, but we are really R newbies who have had great difficulty scraping html data. Sorry about our low levels of contribution, just try to follow the task and give you something to work with, therefore, to link the two stories together.   Hui (Gracie) Han

**Comment by ghh2001** [comment]
It did not seem that we are able to upload files to this issue folder, so will try email instead for now.  Hui (Gracie) Han

**Comment by ghh2001** [comment]
[skills required by occupations.xlsx](https://github.com/simplymathematics/data-skills/files/2499472/skills.required.by.occupations.xlsx)

**Comment by ghh2001** [comment]
Here is the Rmd to read the CSV into dataframe

**Comment by ghh2001** [comment]
title: "Read csv Skill Set Occupation"
author: "Jun (John) Pan"
date: "October 21, 2018"
output: html_document
---


```{r}
library (tidyr)
library (dplyr)
```

```{r}
OccupationsWSkillsRaw <- read.csv ('E:/8-607 Week8 607 GH TO Do Scraping WebPage/skills required by occupations.csv')

```

```{r}
head(OccupationsWSkillsRaw)
tail (OccupationsWSkillsRaw)

```

```{r}
# to get rid of the row 31- 108 (all na)
OccupationsWSkills <- OccupationsWSkillsRaw [1:34,]

```

```{r}
head(OccupationsWSkills)
tail (OccupationsWSkills)
