### ISSUE TITLE
Skills

### ISSUE THREAD

**Issue by simplymathematics** [simplymathematics/data-skills#3]
- [x] Mine Indeed for said skills
- [x] change search to nation wide--I have a feeling NYC's financial services industry might skew the data
- [x] analysis
- [x] pretty graphic
- [x] final test

Do #5

**Comment by simplymathematics** [comment]
- [ ] Justify a list of skills. use [this data](https://www.onetonline.org/link/summary/15-1111.00). Repeat for each 15-00000 occupation.

**Comment by ritwar01** [comment]
I need to fix regex for keyword Search 'R'. It's returning false positive

**Comment by ghh2001** [comment]
> * [x]  Mine Indeed for said skills
> * [ ]  change search to nation wide--I have a feeling NYC's financial services industry might skew the data
> * [x]  analysis
> * [x]  pretty graphic
> * [ ]  final test
> 
> Do #5

HI, this is Gracie. This comments goes to Ravi. I think the Skills vector that Ravi defined for Indeed data mining is a little too narrow.  Currently, it has only 16 elements, when I mined the ONET data for acuries and biostatistician, only 5 of them cross matched.

**Comment by ritwar01** [comment]
Please send me a list of skill sets you want me to add and I'll add it to my vector. I'm trying to making at simple as possible since scrapping these sites take a while.

**Comment by ghh2001** [comment]
Hi, Ravi:
Very appreciated about your reply. We will try to give you something
hopefully tonight.
Gracie han

**Comment by ghh2001** [comment]
Hi, Ravi:
Jun summarized some skills (hard skills) from the ONET website.  The excel
is for your reference.  It is also on the slack. THanks
Gracie

**Comment by simplymathematics** [comment]
Excellent work, @ritwar01!
