### ISSUE TITLE
Skills List

### ISSUE THREAD

**Issue by simplymathematics** [simplymathematics/data-skills#5]
- [x] Get Skills List
- [x] Clean Skills List
- [x] Make dataframe that maps each occupation (row) to each skill

**Comment by simplymathematics** [comment]
@jemceachern I did the first 2 late last night. Can you handle the third one?

There's probably an easy way to do this in tidyr, but you can always brute force it with two for loops. Thanks!

**Comment by jemceach** [comment]
@simplymathematics - I'm on it now 👍
