### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by simplymathematics** [simplymathematics/data-skills#7]
# Presentation
## Prepare Deliverable 
- [x] Create .Rmd file for rpubs
- [x] link to all files at appropriate locations.  
- [x] Document each step
- [x] Create final data frame
- [x] export as csv
- [x] finish .Rpres
- [x] make sure numbers align with output

## Add Content 
- [x] Brief description of the data sources used
- [x] Outline role of each contributing team member
- [x] Describe the question being answered and your conclusions based on your analysis of the data.  
- [x] Bonus: Describe of challenges that you encountered and recommendations for further analysis going forward.

**Comment by ghh2001** [comment]
Charlie:
THank you! Looking forward to seeing the COOL presentation!
Gracie
